parameters:
    tms_rest_client.hypermedia.crawler.class: Tms\Bundle\RestClientBundle\Hypermedia\Crawling\Crawler
    tms_rest_client.hypermedia.crawling_path.class: Tms\Bundle\RestClientBundle\Hypermedia\Crawling\CrawlingPath
    tms_rest_client.hypermedia.hydrator.item.class: Tms\Bundle\RestClientBundle\Hypermedia\Hydratation\HypermediaItemHydrator
    tms_rest_client.hypermedia.hydrator.collection.class: Tms\Bundle\RestClientBundle\Hypermedia\Hydratation\HypermediaCollectionHydrator
    tms_rest_client.hypermedia.hydrator.array.class: Tms\Bundle\RestClientBundle\Hypermedia\Hydratation\HypermediaArrayHydrator
    tms_rest_client.hypermedia.hydratation_handler.class: Tms\Bundle\RestClientBundle\Hypermedia\Hydratation\HypermediaHydratationHandler

services:
    tms_rest_client.hypermedia.crawler:
        class: %tms_rest_client.hypermedia.crawler.class%

    tms_rest_client.hypermedia.crawling_path:
        class: %tms_rest_client.hypermedia.crawling_path.class%
        arguments: [@tms_rest_client.hypermedia.hydratation_handler, null, null]
        abstract: true
        public: false

    tms_rest_client.hypermedia.hydrator.item:
        class: %tms_rest_client.hypermedia.hydrator.item.class%
        public: false
        tags:
            - { name: tms_rest_client.hypermedia.hydrator, id: %tms_rest_client.hypermedia.hydrator.item% }

    tms_rest_client.hypermedia.hydrator.collection:
        class: %tms_rest_client.hypermedia.hydrator.collection.class%
        public: false
        tags:
            - { name: tms_rest_client.hypermedia.hydrator, id: %tms_rest_client.hypermedia.hydrator.collection% }

    tms_rest_client.hypermedia.hydrator.array:
        class: %tms_rest_client.hypermedia.hydrator.array.class%
        public: false
        tags:
            - { name: tms_rest_client.hypermedia.hydrator, id: %tms_rest_client.hypermedia.hydrator.array% }

    tms_rest_client.hypermedia.hydratation_handler:
        class: %tms_rest_client.hypermedia.hydratation_handler.class%
        public: false
