parameters:
    tms_rest_client.crawler.handler.class: Tms\Bundle\RestClientBundle\Crawler\HypermediaCrawlerHandler
    tms_rest_client.crawler.class: Tms\Bundle\RestClientBundle\Crawler\HypermediaCrawler
    tms_rest_client.router.class: Tms\Bundle\RestClientBundle\Router\HypermediaRouter

services:
    tms_rest_client.crawler.handler:
        class: %tms_rest_client.crawler.handler.class%

    tms_rest_client.crawler:
        class: %tms_rest_client.crawler.class%
        arguments: [@da_api_client.api.hypermedia.crawler]

    tms_rest_client.router:
        class: %tms_rest_client.router.class%
        arguments: [@router]